name: helloDart
version: 0.0.1
description: A sample command-line application


environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
